### ISSUE TITLE
When ipapi.co cannot be resolved, container crashes

### ISSUE THREAD

**Issue by nomad64** [QuadStingray/docker-speedtest-influxdb#10]
After the recent changes, I noticed my container instance was constantly running its speed test, then crashing. After some digging, I found that my pihole servers were blocking ipapi.co, which was causing the below crash:
```
2021/02/05 16:45:37 **************************************************************,
2021/02/05 16:45:37 ******** Parser started with following commands **************,
2021/02/05 16:45:37 **  interval 3600,
2021/02/05 16:45:37 **  Distance Unit K,
2021/02/05 16:45:37 **  Host dokpv01,
2021/02/05 16:45:37 **  showExternalIp: true,
2021/02/05 16:45:37 **  influxHost http://grafana.server:8086,
2021/02/05 16:45:37 **  influxDB speedtest,
2021/02/05 16:45:37 **  influxUser influxdb_speedtest,
2021/02/05 16:45:37 **  influxPwd is not Default,
2021/02/05 16:45:37 **************************************************************,
2021/02/05 16:45:37 **************************************************************,
Get "https://ipapi.co/.../json/": dial tcp 0.0.0.0:443: connect: connection refused,
panic: runtime error: invalid memory address or nil pointer dereference,
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x69a68a],
,
goroutine 1 [running]:,
quadstingray/speedtest-influxdb/model.CheckIpLocation(0xc000270000, 0xe, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...),
	/go/src/quadstingray/speedtest-influxdb/model/geoip.go:47 +0x18a,
main.runTest(0xe10, 0x7ffffafa9d7e, 0x7, 0x7ffffafa9d87, 0x0, 0x7ffffafa9dc3, 0x1, 0x10000, 0x1, 0x7ffffafa9cfd, ...),
	/go/src/quadstingray/speedtest-influxdb/app.go:115 +0x26f,
main.main(),
	/go/src/quadstingray/speedtest-influxdb/app.go:42 +0xd8,
```

The main concern with the crash, is it was happening after the speed test was run. Since I had the container configured in Docker Swarm, it automatically restarted the container after it crashed. So it got stuck in a loop where it was running a speed test about once every 20 seconds.

After I whitelisted ipapi.co, the container runs normally.

I am not sure why ipapi.co was on a block list, but perhaps it should run a check to make sure it can resolve it prior to the speed test? Otherwise, more gracefully handle the "connection refused" error?

Docker version for reference:
```
root@dokpv01:~# docker version
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:02:52 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:01:20 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by QuadStingray** [comment]
geoip with version 1.1.0 with better error handling.
When ipapi.co not reachable distance is 0.
